core:
  mode: release
  log:
    level: info
    path: ./logs/metrics-post-station
    maxsize: 100
    maxage: 7
    compress: true

apiserver:
  listen: :9091
  prefix: /
  redis:
    addr: 192.168.221.130:6379
    password: 123456
    db: 0
    dialtimeout: 5
  metrics:
    enable: true
    path: /self-metrics
